export const products = [
  {
    id: 1,
    title: "Essence Mascara Lash Princess",
    description:
      "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
    category: "beauty",
    price: 9.99,
    discountPercentage: 7.17,
    rating: 4.94,
    stock: 5,
    tags: ["beauty", "mascara"],
    brand: "Essence",
    sku: "RCH45Q1A",
    weight: 2,
    dimensions: {
      width: 23.17,
      height: 14.43,
      depth: 28.01,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "John Doe",
        reviewerEmail: "john.doe@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Not as described!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Scarlett Wright",
        reviewerEmail: "scarlett.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 24,
    meta: {
      createdAt: "2024-05-23T08:56:21.618Z",
      updatedAt: "2024-05-23T08:56:21.618Z",
      barcode: "9164035109868",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png",
  },
  {
    id: 2,
    title: "Eyeshadow Palette with Mirror",
    description:
      "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
    category: "beauty",
    price: 19.99,
    discountPercentage: 5.5,
    rating: 3.28,
    stock: 44,
    tags: ["beauty", "eyeshadow"],
    brand: "Glamour Beauty",
    sku: "MVCFH27F",
    weight: 3,
    dimensions: {
      width: 12.42,
      height: 8.63,
      depth: 29.13,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Liam Garcia",
        reviewerEmail: "liam.garcia@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Very disappointed!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Nora Russell",
        reviewerEmail: "nora.russell@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 32,
    meta: {
      createdAt: "2024-05-23T08:56:21.618Z",
      updatedAt: "2024-05-23T08:56:21.618Z",
      barcode: "2817839095220",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/thumbnail.png",
  },
  {
    id: 3,
    title: "Powder Canister",
    description:
      "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
    category: "beauty",
    price: 14.99,
    discountPercentage: 18.14,
    rating: 3.82,
    stock: 59,
    tags: ["beauty", "face powder"],
    brand: "Velvet Touch",
    sku: "9EN8WLT2",
    weight: 8,
    dimensions: {
      width: 24.16,
      height: 10.7,
      depth: 11.07,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Ethan Thompson",
        reviewerEmail: "ethan.thompson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Levi Hicks",
        reviewerEmail: "levi.hicks@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Hazel Gardner",
        reviewerEmail: "hazel.gardner@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 25,
    meta: {
      createdAt: "2024-05-23T08:56:21.618Z",
      updatedAt: "2024-05-23T08:56:21.618Z",
      barcode: "0516267971277",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/thumbnail.png",
  },
  {
    id: 4,
    title: "Red Lipstick",
    description:
      "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
    category: "beauty",
    price: 12.99,
    discountPercentage: 19.03,
    rating: 2.51,
    stock: 68,
    tags: ["beauty", "lipstick"],
    brand: "Chic Cosmetics",
    sku: "O5IF1NTA",
    weight: 5,
    dimensions: {
      width: 14.37,
      height: 13.94,
      depth: 14.6,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Leo Rivera",
        reviewerEmail: "leo.rivera@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Oscar Powers",
        reviewerEmail: "oscar.powers@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Carter Rivera",
        reviewerEmail: "carter.rivera@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 6,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "9444582199406",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/thumbnail.png",
  },
  {
    id: 5,
    title: "Red Nail Polish",
    description:
      "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
    category: "beauty",
    price: 8.99,
    discountPercentage: 2.46,
    rating: 3.91,
    stock: 71,
    tags: ["beauty", "nail polish"],
    brand: "Nail Couture",
    sku: "YUIIIP4W",
    weight: 9,
    dimensions: {
      width: 8.11,
      height: 10.89,
      depth: 29.06,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Leo Rivera",
        reviewerEmail: "leo.rivera@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Evan Reed",
        reviewerEmail: "evan.reed@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Evelyn Sanchez",
        reviewerEmail: "evelyn.sanchez@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 46,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "3212847902461",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/thumbnail.png",
  },
  {
    id: 6,
    title: "Calvin Klein CK One",
    description:
      "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
    category: "fragrances",
    price: 49.99,
    discountPercentage: 0.32,
    rating: 4.85,
    stock: 17,
    tags: ["fragrances", "perfumes"],
    brand: "Calvin Klein",
    sku: "DZM2JQZE",
    weight: 5,
    dimensions: {
      width: 11.53,
      height: 14.44,
      depth: 6.81,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Sophia Brown",
        reviewerEmail: "sophia.brown@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Very disappointed!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Maya Reed",
        reviewerEmail: "maya.reed@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 20,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "2210136215089",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/thumbnail.png",
  },
  {
    id: 7,
    title: "Chanel Coco Noir Eau De",
    description:
      "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
    category: "fragrances",
    price: 129.99,
    discountPercentage: 18.64,
    rating: 2.76,
    stock: 41,
    tags: ["fragrances", "perfumes"],
    brand: "Chanel",
    sku: "K71HBCGS",
    weight: 4,
    dimensions: {
      width: 21.27,
      height: 28,
      depth: 11.89,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Disappointing product!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Lincoln Kelly",
        reviewerEmail: "lincoln.kelly@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Lincoln Kelly",
        reviewerEmail: "lincoln.kelly@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Lucas Allen",
        reviewerEmail: "lucas.allen@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "1435582999795",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/thumbnail.png",
  },
  {
    id: 8,
    title: "Dior J'adore",
    description:
      "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
    category: "fragrances",
    price: 89.99,
    discountPercentage: 17.44,
    rating: 3.31,
    stock: 91,
    tags: ["fragrances", "perfumes"],
    brand: "Dior",
    sku: "E70NB03B",
    weight: 10,
    dimensions: {
      width: 21.51,
      height: 7,
      depth: 26.51,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Zoe Nicholson",
        reviewerEmail: "zoe.nicholson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Addison Wright",
        reviewerEmail: "addison.wright@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 8,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "0887083199279",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/thumbnail.png",
  },
  {
    id: 9,
    title: "Dolce Shine Eau de",
    description:
      "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
    category: "fragrances",
    price: 69.99,
    discountPercentage: 11.47,
    rating: 2.68,
    stock: 3,
    tags: ["fragrances", "perfumes"],
    brand: "Dolce & Gabbana",
    sku: "1NBFK980",
    weight: 5,
    dimensions: {
      width: 17,
      height: 24.57,
      depth: 13.3,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Xavier Wright",
        reviewerEmail: "xavier.wright@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Mila Hernandez",
        reviewerEmail: "mila.hernandez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Sophia Brown",
        reviewerEmail: "sophia.brown@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 9,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "1939383392674",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/thumbnail.png",
  },
  {
    id: 10,
    title: "Gucci Bloom Eau de",
    description:
      "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
    category: "fragrances",
    price: 79.99,
    discountPercentage: 8.9,
    rating: 2.69,
    stock: 93,
    tags: ["fragrances", "perfumes"],
    brand: "Gucci",
    sku: "FFKZ6HOF",
    weight: 10,
    dimensions: {
      width: 22.28,
      height: 17.81,
      depth: 27.18,
    },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Aria Parker",
        reviewerEmail: "aria.parker@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Natalie Harris",
        reviewerEmail: "natalie.harris@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ava Harris",
        reviewerEmail: "ava.harris@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "8232190382069",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/thumbnail.png",
  },
  {
    id: 11,
    title: "Annibale Colombo Bed",
    description:
      "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
    category: "furniture",
    price: 1899.99,
    discountPercentage: 0.29,
    rating: 4.14,
    stock: 47,
    tags: ["furniture", "beds"],
    brand: "Annibale Colombo",
    sku: "4KMDTZWF",
    weight: 3,
    dimensions: {
      width: 28.75,
      height: 26.88,
      depth: 24.47,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Julian Newton",
        reviewerEmail: "julian.newton@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "7113807059215",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/thumbnail.png",
  },
  {
    id: 12,
    title: "Annibale Colombo Sofa",
    description:
      "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
    category: "furniture",
    price: 2499.99,
    discountPercentage: 18.54,
    rating: 3.08,
    stock: 16,
    tags: ["furniture", "sofas"],
    brand: "Annibale Colombo",
    sku: "LUU95CQP",
    weight: 3,
    dimensions: {
      width: 20.97,
      height: 19.11,
      depth: 25.81,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Tyler Davis",
        reviewerEmail: "tyler.davis@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Hannah Robinson",
        reviewerEmail: "hannah.robinson@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Waste of money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "0426785817074",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/thumbnail.png",
  },
  {
    id: 13,
    title: "Bedside Table African Cherry",
    description:
      "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
    category: "furniture",
    price: 299.99,
    discountPercentage: 9.58,
    rating: 4.48,
    stock: 16,
    tags: ["furniture", "bedside tables"],
    brand: "Furniture Co.",
    sku: "OWPLTZYX",
    weight: 10,
    dimensions: {
      width: 25.43,
      height: 20.2,
      depth: 24.95,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "John Doe",
        reviewerEmail: "john.doe@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Avery Carter",
        reviewerEmail: "avery.carter@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Evelyn Sanchez",
        reviewerEmail: "evelyn.sanchez@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "2913244159666",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/thumbnail.png",
  },
  {
    id: 14,
    title: "Knoll Saarinen Executive Conference Chair",
    description:
      "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
    category: "furniture",
    price: 499.99,
    discountPercentage: 15.23,
    rating: 4.11,
    stock: 47,
    tags: ["furniture", "office chairs"],
    brand: "Knoll",
    sku: "RKHVJ4FE",
    weight: 3,
    dimensions: {
      width: 16.59,
      height: 21.46,
      depth: 29.07,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Leah Gutierrez",
        reviewerEmail: "leah.gutierrez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Waste of money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Stella Morris",
        reviewerEmail: "stella.morris@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "0726316339746",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/thumbnail.png",
  },
  {
    id: 15,
    title: "Wooden Bathroom Sink With Mirror",
    description:
      "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
    category: "furniture",
    price: 799.99,
    discountPercentage: 11.22,
    rating: 3.26,
    stock: 95,
    tags: ["furniture", "bathroom"],
    brand: "Bath Trends",
    sku: "7OLTIEVO",
    weight: 6,
    dimensions: {
      width: 7.32,
      height: 22.64,
      depth: 12.37,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Charlotte Lopez",
        reviewerEmail: "charlotte.lopez@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "William Gonzalez",
        reviewerEmail: "william.gonzalez@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Not worth the price!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ava Harrison",
        reviewerEmail: "ava.harrison@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "7839797529453",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/thumbnail.png",
  },
  {
    id: 16,
    title: "Apple",
    description:
      "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
    category: "groceries",
    price: 1.99,
    discountPercentage: 1.97,
    rating: 2.96,
    stock: 9,
    tags: ["fruits"],
    sku: "QTROUV79",
    weight: 8,
    dimensions: {
      width: 8.29,
      height: 5.58,
      depth: 12.41,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Logan Lee",
        reviewerEmail: "logan.lee@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Elena Long",
        reviewerEmail: "elena.long@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Not as described!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Grayson Coleman",
        reviewerEmail: "grayson.coleman@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 44,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "2517819903837",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/products/images/groceries/Apple/1.png"],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Apple/thumbnail.png",
  },
  {
    id: 17,
    title: "Beef Steak",
    description:
      "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
    category: "groceries",
    price: 12.99,
    discountPercentage: 17.99,
    rating: 2.83,
    stock: 96,
    tags: ["meat"],
    sku: "BWWA2MSO",
    weight: 9,
    dimensions: {
      width: 23.35,
      height: 13.48,
      depth: 26.4,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ethan Martinez",
        reviewerEmail: "ethan.martinez@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Disappointing product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Owen Fisher",
        reviewerEmail: "owen.fisher@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Scarlett Wright",
        reviewerEmail: "scarlett.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 21,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "8335515097879",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Beef%20Steak/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Beef%20Steak/thumbnail.png",
  },
  {
    id: 18,
    title: "Cat Food",
    description:
      "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
    category: "groceries",
    price: 8.99,
    discountPercentage: 9.57,
    rating: 2.88,
    stock: 13,
    tags: ["pet supplies", "cat food"],
    sku: "C3F8QN6O",
    weight: 9,
    dimensions: {
      width: 15.4,
      height: 13.97,
      depth: 25.13,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Mateo Bennett",
        reviewerEmail: "mateo.bennett@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Aurora Barnes",
        reviewerEmail: "aurora.barnes@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ellie Stewart",
        reviewerEmail: "ellie.stewart@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 48,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "5503491330693",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/thumbnail.png",
  },
  {
    id: 19,
    title: "Chicken Meat",
    description:
      "Fresh and tender chicken meat, suitable for various culinary preparations.",
    category: "groceries",
    price: 9.99,
    discountPercentage: 10.46,
    rating: 4.61,
    stock: 69,
    tags: ["meat"],
    sku: "G5YEHW7B",
    weight: 7,
    dimensions: {
      width: 15.96,
      height: 29.24,
      depth: 26.25,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Sophia Jones",
        reviewerEmail: "sophia.jones@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Maya Reed",
        reviewerEmail: "maya.reed@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Harper Turner",
        reviewerEmail: "harper.turner@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 46,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "0966223559510",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/1.png",
      "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/2.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/thumbnail.png",
  },
  {
    id: 20,
    title: "Cooking Oil",
    description:
      "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
    category: "groceries",
    price: 4.99,
    discountPercentage: 18.89,
    rating: 4.01,
    stock: 22,
    tags: ["cooking essentials"],
    sku: "Q6ZP1UY8",
    weight: 8,
    dimensions: {
      width: 8.18,
      height: 27.45,
      depth: 27.88,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Mason Parker",
        reviewerEmail: "mason.parker@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Jonathan Pierce",
        reviewerEmail: "jonathan.pierce@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Alexander Hernandez",
        reviewerEmail: "alexander.hernandez@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "6707669443381",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Cooking%20Oil/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Cooking%20Oil/thumbnail.png",
  },
  {
    id: 21,
    title: "Cucumber",
    description:
      "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
    category: "groceries",
    price: 1.49,
    discountPercentage: 11.44,
    rating: 4.71,
    stock: 22,
    tags: ["vegetables"],
    sku: "6KGF2K6Z",
    weight: 9,
    dimensions: {
      width: 11.04,
      height: 20.5,
      depth: 8.18,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Elijah Hill",
        reviewerEmail: "elijah.hill@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Liam Garcia",
        reviewerEmail: "liam.garcia@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ella Cook",
        reviewerEmail: "ella.cook@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 7,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "2597004869708",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Cucumber/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Cucumber/thumbnail.png",
  },
  {
    id: 22,
    title: "Dog Food",
    description:
      "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
    category: "groceries",
    price: 10.99,
    discountPercentage: 18.15,
    rating: 2.74,
    stock: 40,
    tags: ["pet supplies", "dog food"],
    sku: "A6QRCH37",
    weight: 2,
    dimensions: {
      width: 29.39,
      height: 29.77,
      depth: 20.54,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Leo Rivera",
        reviewerEmail: "leo.rivera@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Alexander Jones",
        reviewerEmail: "alexander.jones@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Addison Wright",
        reviewerEmail: "addison.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 29,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "7957222289508",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Dog%20Food/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Dog%20Food/thumbnail.png",
  },
  {
    id: 23,
    title: "Eggs",
    description:
      "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
    category: "groceries",
    price: 2.99,
    discountPercentage: 5.8,
    rating: 4.46,
    stock: 10,
    tags: ["dairy"],
    sku: "YA617RI7",
    weight: 4,
    dimensions: {
      width: 12.3,
      height: 10.99,
      depth: 15.53,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Mateo Perez",
        reviewerEmail: "mateo.perez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Cameron Perez",
        reviewerEmail: "cameron.perez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Aurora Barnes",
        reviewerEmail: "aurora.barnes@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 43,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "7095702028776",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/products/images/groceries/Eggs/1.png"],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Eggs/thumbnail.png",
  },
  {
    id: 24,
    title: "Fish Steak",
    description:
      "Quality fish steak, suitable for grilling, baking, or pan-searing.",
    category: "groceries",
    price: 14.99,
    discountPercentage: 7,
    rating: 4.83,
    stock: 99,
    tags: ["seafood"],
    sku: "XNIH1MTA",
    weight: 8,
    dimensions: {
      width: 20.14,
      height: 8.4,
      depth: 10.01,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Michael Johnson",
        reviewerEmail: "michael.johnson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Julian Newton",
        reviewerEmail: "julian.newton@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Lila Hudson",
        reviewerEmail: "lila.hudson@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 49,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "4250692197342",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/thumbnail.png",
  },
  {
    id: 25,
    title: "Green Bell Pepper",
    description:
      "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
    category: "groceries",
    price: 1.29,
    discountPercentage: 15.5,
    rating: 4.28,
    stock: 89,
    tags: ["vegetables"],
    sku: "HU7S7VQ0",
    weight: 7,
    dimensions: {
      width: 7.32,
      height: 14.31,
      depth: 21.38,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Maya Reed",
        reviewerEmail: "maya.reed@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ethan Thompson",
        reviewerEmail: "ethan.thompson@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "7583442707568",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/thumbnail.png",
  },
  {
    id: 26,
    title: "Green Chili Pepper",
    description:
      "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
    category: "groceries",
    price: 0.99,
    discountPercentage: 18.51,
    rating: 4.43,
    stock: 8,
    tags: ["vegetables"],
    sku: "Y4RM3JCB",
    weight: 2,
    dimensions: {
      width: 18.67,
      height: 21.17,
      depth: 25.26,
    },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Disappointing product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Mateo Bennett",
        reviewerEmail: "mateo.bennett@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Natalie Price",
        reviewerEmail: "natalie.price@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Avery Barnes",
        reviewerEmail: "avery.barnes@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 43,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "8400326844874",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/thumbnail.png",
  },
  {
    id: 27,
    title: "Honey Jar",
    description:
      "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
    category: "groceries",
    price: 6.99,
    discountPercentage: 1.91,
    rating: 3.5,
    stock: 25,
    tags: ["condiments"],
    sku: "BTBNIIOU",
    weight: 9,
    dimensions: {
      width: 26.53,
      height: 27.11,
      depth: 6.63,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Awesome product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Gabriel Hayes",
        reviewerEmail: "gabriel.hayes@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "James Garcia",
        reviewerEmail: "james.garcia@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "0668665656044",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Honey%20Jar/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Honey%20Jar/thumbnail.png",
  },
  {
    id: 28,
    title: "Ice Cream",
    description:
      "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
    category: "groceries",
    price: 5.49,
    discountPercentage: 7.58,
    rating: 3.77,
    stock: 76,
    tags: ["desserts"],
    sku: "VEZMU1EQ",
    weight: 5,
    dimensions: {
      width: 17.66,
      height: 24.49,
      depth: 25.98,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Madeline Simpson",
        reviewerEmail: "madeline.simpson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Caleb Nelson",
        reviewerEmail: "caleb.nelson@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 19,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "9603960319256",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/1.png",
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/2.png",
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/3.png",
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/4.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/thumbnail.png",
  },
  {
    id: 29,
    title: "Juice",
    description:
      "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
    category: "groceries",
    price: 3.99,
    discountPercentage: 5.45,
    rating: 3.41,
    stock: 99,
    tags: ["beverages"],
    sku: "M2K19S06",
    weight: 2,
    dimensions: {
      width: 8.97,
      height: 12.26,
      depth: 15.05,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Leo Rivera",
        reviewerEmail: "leo.rivera@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Not worth the price!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ethan Martinez",
        reviewerEmail: "ethan.martinez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Max Parker",
        reviewerEmail: "max.parker@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 26,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "8546824122355",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/products/images/groceries/Juice/1.png"],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Juice/thumbnail.png",
  },
  {
    id: 30,
    title: "Kiwi",
    description:
      "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
    category: "groceries",
    price: 2.49,
    discountPercentage: 10.32,
    rating: 4.37,
    stock: 1,
    tags: ["fruits"],
    sku: "0X3NORB9",
    weight: 8,
    dimensions: {
      width: 27.3,
      height: 7.48,
      depth: 15.08,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Nora Russell",
        reviewerEmail: "nora.russell@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Dylan Wells",
        reviewerEmail: "dylan.wells@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Noah Hernandez",
        reviewerEmail: "noah.hernandez@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 8,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "3325493172934",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/products/images/groceries/Kiwi/1.png"],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Kiwi/thumbnail.png",
  },
];

export const productsTwo = [
  {
    id: "B0CWXNS552",
    product_title: "Apple AirTag",
    product_price: 24.99,
    product_original_price: "$29.00",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 2027,
    product_url: "https://www.amazon.com/dp/B0CWXNS552",
    product_photo:
      "https://m.media-amazon.com/images/I/71rP7f78eFL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 11,
    product_minimum_offer_price: "$23.33",
    is_best_seller: false,
    is_amazon_choice: true,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "B0D5FZGY8W",
    product_title:
      "URO Vaginal Probiotics for Women pH Balance with Prebiotics &amp; Lactobacillus Probiotic Blend - Women&#x27;s Vaginal Health Supplement - Promote Healthy Vaginal Odor &amp; Vaginal Flora, 60 Count (Pack of 1)",
    product_price: 28.79,
    unit_price: "$10.48",
    unit_count: 60,
    product_original_price: "$31.99",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 376,
    product_url: "https://www.amazon.com/dp/B0D5FZGY8W",
    product_photo:
      "https://m.media-amazon.com/images/I/61tYAHJi3LL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$28.79",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: "100K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "1665955430",
    product_title: "Reckless (The Powerless Trilogy)",
    product_price: 14.97,
    product_original_price: "$21.99",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 2160,
    product_url: "https://www.amazon.com/dp/1665955430",
    product_photo:
      "https://m.media-amazon.com/images/I/81q6ecxcZUL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 37,
    product_minimum_offer_price: "$14.96",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "B0CS12LZLS",
    product_title: "NESCAFÉ Gold Espresso Blonde, Instant Coffee, 3.5 oz",
    product_price: 6.68,
    unit_price: "$1.91",
    unit_count: 3,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 278,
    product_url: "https://www.amazon.com/dp/B0CS12LZLS",
    product_photo:
      "https://m.media-amazon.com/images/I/71tPLfAANDL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$6.68",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery:
      "FREE delivery Jul 15 - 17 on $35 of items shipped by AmazonOr fastest delivery Jul 14 - 16",
    has_variations: false,
  },
  {
    id: "B0CSBZVR6F",
    product_title:
      "2 Pack Continuous Spray Bottles - Ultra Fine Mist Sprayer | Water Spray Bottle For Hair Mister Spray Bottle | Hair Spray Bottles For Hairstyling, Cleaning, Salons - 2pk 6.8 OZ / 200 ML",
    product_price: 8.48,
    product_original_price: "$8.99",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 2110,
    product_url: "https://www.amazon.com/dp/B0CSBZVR6F",
    product_photo:
      "https://m.media-amazon.com/images/I/71Grc+h-AtL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 5,
    product_minimum_offer_price: "$2.45",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: "20K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "1668032147",
    product_title: "Protocols: An Operating Manual for the Human Body",
    product_price: 21.39,
    product_original_price: "$35.00",
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/1668032147",
    product_photo:
      "https://m.media-amazon.com/images/I/61tDi3+vgzL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$21.39",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery:
      "FREE delivery Mon, Apr 28, 2025 on $35 of items shipped by AmazonOr fastest delivery Tue, Apr 22, 2025 This title will be released on April 22, 2025.",
    has_variations: false,
  },
  {
    id: "0593657470",
    product_title: "On Call: A Doctor&#x27;s Journey in Public Service",
    product_price: 22.59,
    product_original_price: "$36.00",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 780,
    product_url: "https://www.amazon.com/dp/0593657470",
    product_photo:
      "https://m.media-amazon.com/images/I/813MUJ9ftIL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$22.59",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "B0CV4FQPY1",
    product_title:
      "Bounty Select-A-Size Paper Towels, White, 8 Triple Rolls = 24 Regular Rolls",
    product_price: 22.18,
    unit_price: "$2.05",
    unit_count: 11,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 35935,
    product_url: "https://www.amazon.com/dp/B0CV4FQPY1",
    product_photo:
      "https://m.media-amazon.com/images/I/81jYzN4cAdL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 15,
    product_minimum_offer_price: "$21.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "40K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "B0C9N2L56X",
    product_title:
      "The Anxious Generation: How the Great Rewiring of Childhood Is Causing an Epidemic of Mental Illness",
    product_price: 12.0,
    product_original_price: "$20.25",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 1764,
    product_url: "https://www.amazon.com/dp/B0C9N2L56X",
    product_photo:
      "https://m.media-amazon.com/images/I/81N4drWaxuL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    id: "1464221138",
    product_title: "The Housemaid Is Watching",
    product_price: 12.71,
    product_original_price: "$17.99",
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 56803,
    product_url: "https://www.amazon.com/dp/1464221138",
    product_photo:
      "https://m.media-amazon.com/images/I/91OSM58Y-pL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 52,
    product_minimum_offer_price: "$10.50",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "B0CSYG2CP3",
    product_title:
      "Car Carplay Cable for iPhone 15 15 Pro Max 15 Plus Cable, USB A to USB C for Carplay USB C Cord, iPad usb C Cable 10th Gen iPad Pro iPad Air 5th 4th Mini 6th Gen Car Charger Cable Cord Replacement 3FT",
    product_price: 8.19,
    product_original_price: "$8.99",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 596,
    product_url: "https://www.amazon.com/dp/B0CSYG2CP3",
    product_photo:
      "https://m.media-amazon.com/images/I/61fpyOCUDML._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$8.19",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "B07RFSSYBH",
    product_title:
      "Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones",
    product_price: 11.0,
    product_original_price: "$18.00",
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 129547,
    product_url: "https://www.amazon.com/dp/B07RFSSYBH",
    product_photo:
      "https://m.media-amazon.com/images/I/71F4+7rk2eL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    id: "B0CQDFPMQW",
    product_title:
      "LMNT Zero-Sugar Electrolytes - Variety Pack Bundle - Drink Mix | No Dodgy Ingredients | Keto &amp; Paleo Friendly | 36 Sticks",
    product_price: 59.99,
    unit_price: "$7.90",
    unit_count: 8,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 17598,
    product_url: "https://www.amazon.com/dp/B0CQDFPMQW",
    product_photo:
      "https://m.media-amazon.com/images/I/81qGH-6amTL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$59.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "20K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10",
    has_variations: false,
  },
  {
    id: "B0CP93N5S2",
    product_title: "All the Colors of the Dark",
    product_price: 13.99,
    product_original_price: "$30.00",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 856,
    product_url: "https://www.amazon.com/dp/B0CP93N5S2",
    product_photo:
      "https://m.media-amazon.com/images/I/81RBcyIyl2L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$13.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Print List Price: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    id: "B0D3PBB78P",
    product_title: "EA SPORTS College Football 25 - PlayStation 5",
    product_price: 69.99,
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D3PBB78P",
    product_photo:
      "https://m.media-amazon.com/images/I/81aE0GBL2mL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$69.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 19, 2024",
    delivery: "FREE deliveryThis item will be released on July 19, 2024.",
    has_variations: false,
  },
  {
    id: "B0D49X2P79",
    product_title: "Twister [4K UHD]",
    product_price: 24.96,
    product_original_price: "$33.99",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 2119,
    product_url: "https://www.amazon.com/dp/B0D49X2P79",
    product_photo:
      "https://m.media-amazon.com/images/I/71HH+CAgaJL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$24.96",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery:
      "FREE delivery Wed, Jul 17 on $35 of items shipped by AmazonOr fastest delivery Tue, Jul 16 This title will be released on July 9, 2024.",
    has_variations: false,
  },
  {
    id: "B0CLKQF5HR",
    product_title: "Swan Song",
    product_price: 14.99,
    product_original_price: "$30.00",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 7102,
    product_url: "https://www.amazon.com/dp/B0CLKQF5HR",
    product_photo:
      "https://m.media-amazon.com/images/I/71dSn3QCY6L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$14.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Print List Price: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    id: "B0D2PKQGQV",
    product_title:
      "Hanes Men&#x27;s Pocket Undershirt Pack, Cotton Crew Neck T-Shirt, Moisture Wicking Tee, Assorted 6-Pack",
    product_price: 21.98,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 24675,
    product_url: "https://www.amazon.com/dp/B0D2PKQGQV",
    product_photo:
      "https://m.media-amazon.com/images/I/81v4ewQrCgL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$21.98",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "500+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: true,
  },
  {
    id: "B0D1P158BH",
    product_title: "UEFA EURO 2024 Official",
    product_price: 7.0,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.4",
    product_num_ratings: 56,
    product_url: "https://www.amazon.com/dp/B0D1P158BH",
    product_photo:
      "https://m.media-amazon.com/images/I/71Eq+TtkQRL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jun 14, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    id: "B0D74SZ9NS",
    product_title: "Metal Gear Solid Selections Original Soundtrack",
    product_price: 54.98,
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D74SZ9NS",
    product_photo:
      "https://m.media-amazon.com/images/I/81TEJmhug0L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$54.98",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: null,
    delivery:
      "FREE delivery Tue, Oct 22 Or fastest delivery Fri, Oct 18 This title will be released on October 18, 2024.",
    has_variations: false,
  },
  {
    id: "B0D7MC3XH1",
    product_title: "YOYO School: YOYO Doll School life Dress up",
    product_price: 12.0,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 3,
    product_url: "https://www.amazon.com/dp/B0D7MC3XH1",
    product_photo:
      "https://m.media-amazon.com/images/I/81m++AruMtL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jun 20, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    id: "B0CZ7NKH1T",
    product_title: "Triviascapes: relaxing trivia &amp; IQ quiz",
    product_price: 9.0,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 23,
    product_url: "https://www.amazon.com/dp/B0CZ7NKH1T",
    product_photo:
      "https://m.media-amazon.com/images/I/71DhfojGRZL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Apr 10, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    id: "B0CGVSQHNG",
    product_title: "Deeper Than the Dead (Vera Boyett Book 1)",
    product_price: 4.99,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 171,
    product_url: "https://www.amazon.com/dp/B0CGVSQHNG",
    product_photo:
      "https://m.media-amazon.com/images/I/817KwFYx4gL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$4.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "This title will be released on August 1, 2024.",
    has_variations: false,
  },
  {
    id: "B0D81GQ96G",
    product_title: "Smarter IP-TV : Player Pro",
    product_price: 12.99,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.8",
    product_num_ratings: 4,
    product_url: "https://www.amazon.com/dp/B0D81GQ96G",
    product_photo:
      "https://m.media-amazon.com/images/I/61jFyIhWbTL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$12.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jun 26, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    id: "B0D8K3Z4FT",
    product_title:
      "Ys Memoire The Oath of Felghana Nintendo Switch - D1 Refined Edition",
    product_price: 59.99,
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D8K3Z4FT",
    product_photo:
      "https://m.media-amazon.com/images/I/71LhvZ3JUpL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$59.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Mar 31, 2025",
    delivery: "FREE deliveryThis item will be released on March 31, 2025.",
    has_variations: false,
  },
  {
    id: "1538742578",
    product_title: "The Housemaid",
    product_price: 6.96,
    product_original_price: "$12.99",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 319190,
    product_url: "https://www.amazon.com/dp/1538742578",
    product_photo:
      "https://m.media-amazon.com/images/I/81AHTyq2wVL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 119,
    product_minimum_offer_price: "$3.06",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "B0D73NMM7N",
    product_title: "Fluvsies Merge Party",
    product_price: 0.0,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 2,
    product_url: "https://www.amazon.com/dp/B0D73NMM7N",
    product_photo:
      "https://m.media-amazon.com/images/I/81k3RzdCdxL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jun 27, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    id: "B0D7W5JY1Y",
    product_title:
      "Paramount Presents: Bringing Out the Dead [4K UHD + Blu-Ray + Digital Copy]",
    product_price: 39.99,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 1119,
    product_url: "https://www.amazon.com/dp/B0D7W5JY1Y",
    product_photo:
      "https://m.media-amazon.com/images/I/61pWQhd0-hL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$39.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery:
      "FREE delivery Mon, Sep 23 Or fastest delivery Tue, Sep 17 This title will be released on September 17, 2024.",
    has_variations: false,
  },
  {
    id: "B0CKNM2RS7",
    product_title: "Eruption",
    product_price: 6.0,
    product_original_price: "$21.83",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 9813,
    product_url: "https://www.amazon.com/dp/B0CKNM2RS7",
    product_photo:
      "https://m.media-amazon.com/images/I/91jZ4396SPL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    id: "B0D8J9HYGD",
    product_title:
      "Kingdom Of The Planet Of The Apes - UHD/BD Combo + Digital + Steelbook [4K UHD]",
    product_price: 65.99,
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D8J9HYGD",
    product_photo:
      "https://m.media-amazon.com/images/I/81O+BMeRFsL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$65.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery:
      "$10.21 delivery Tue, Aug 27 This title will be released on August 27, 2024.",
    has_variations: false,
  },
  {
    id: "B0D1XD1ZV3",
    product_title:
      "Apple AirPods Pro (2nd Generation) Wireless Ear Buds with USB-C Charging, Up to 2X More Active Noise Cancelling Bluetooth Headphones, Transparency Mode, Adaptive Audio, Personalized Spatial Audio",
    product_price: 249.0,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 1009,
    product_url: "https://www.amazon.com/dp/B0D1XD1ZV3",
    product_photo:
      "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 5,
    product_minimum_offer_price: "$206.80",
    is_best_seller: false,
    is_amazon_choice: true,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10",
    has_variations: false,
  },
  {
    id: "B0D7TY6C1H",
    product_title:
      "Late Night With the Devil - Limited Edition Steelbook [Blu-Ray]",
    product_price: 35.68,
    product_original_price: "$49.99",
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D7TY6C1H",
    product_photo: null,
    product_num_offers: 1,
    product_minimum_offer_price: "$35.68",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "500+ bought in past month",
    delivery:
      "FREE delivery Mon, Sep 16 Or fastest delivery Tue, Sep 10 This title will be released on September 10, 2024.",
    has_variations: false,
  },
  {
    id: "B0CQYH6LQ9",
    product_title:
      "8 Pack Refill Cartridge Kit Compatible with ZEVO Plug-in Light M364 and Max, Replacement 100% Fit (8 Refill Cartridges)",
    product_price: 15.29,
    unit_price: "$1.91",
    unit_count: 8,
    product_original_price: "$17.99",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 1420,
    product_url: "https://www.amazon.com/dp/B0CQYH6LQ9",
    product_photo:
      "https://m.media-amazon.com/images/I/71iEIPz+JSL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$15.29",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "40K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "B0D7KR99VL",
    product_title: "Get unlimited Free Robux 2024",
    product_price: 19.0,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "1",
    product_num_ratings: 2,
    product_url: "https://www.amazon.com/dp/B0D7KR99VL",
    product_photo:
      "https://m.media-amazon.com/images/I/71H3ahAWJHL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jun 20, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    id: "B0CPWYVX6H",
    product_title: "Energizer 2450 Lithium Coin Battery, 2 Pack",
    product_price: 5.44,
    unit_price: "$2.72",
    unit_count: 2,
    product_original_price: "$8.98",
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 1570,
    product_url: "https://www.amazon.com/dp/B0CPWYVX6H",
    product_photo:
      "https://m.media-amazon.com/images/I/71LSsuHdVBL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 11,
    product_minimum_offer_price: "$5.42",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Jul 11 - 15",
    has_variations: false,
  },
  {
    id: "B0CX9CM41G",
    product_title: "Block Mini Craft Village",
    product_price: 4.0,
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0CX9CM41G",
    product_photo:
      "https://m.media-amazon.com/images/I/81H6mknKhaL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "May 31, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    id: "B00OZP5VRS",
    product_title: "A Court of Thorns and Roses",
    product_price: 8.21,
    product_original_price: "$15.20",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 215583,
    product_url: "https://www.amazon.com/dp/B00OZP5VRS",
    product_photo:
      "https://m.media-amazon.com/images/I/81A-T+X6ukL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$8.21",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Digital List Price: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    id: "B0D4FBLRTC",
    product_title: "People Sandbox Playgrounds",
    product_price: 12.0,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "1.8",
    product_num_ratings: 3,
    product_url: "https://www.amazon.com/dp/B0D4FBLRTC",
    product_photo:
      "https://m.media-amazon.com/images/I/51vhEIwynYL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "May 17, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    id: "B0D8JTTX3D",
    product_title: "The Chronicles Of Riddick 4K UHD",
    product_price: 49.95,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 7745,
    product_url: "https://www.amazon.com/dp/B0D8JTTX3D",
    product_photo:
      "https://m.media-amazon.com/images/I/8115yTKlBCL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$49.95",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "500+ bought in past month",
    delivery:
      "FREE delivery Mon, Sep 23 Or fastest delivery Tue, Sep 17 This title will be released on September 17, 2024.",
    has_variations: false,
  },
  {
    id: "B0C4QD5VPB",
    product_title: "The Women: A Novel",
    product_price: 22.0,
    product_original_price: "$24.74",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 124461,
    product_url: "https://www.amazon.com/dp/B0C4QD5VPB",
    product_photo:
      "https://m.media-amazon.com/images/I/91mP3553EzL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    id: "B0CCPPQ38D",
    product_title: "Funny Story",
    product_price: 12.0,
    product_original_price: "$20.25",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 42953,
    product_url: "https://www.amazon.com/dp/B0CCPPQ38D",
    product_photo:
      "https://m.media-amazon.com/images/I/71MmozgfmVL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    id: "B0D37QVQW4",
    product_title: "MLB: Baseball Super League",
    product_price: 53.0,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 51,
    product_url: "https://www.amazon.com/dp/B0D37QVQW4",
    product_photo:
      "https://m.media-amazon.com/images/I/81LYuFcyLlL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "May 24, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    id: "B0D3VHPLW1",
    product_title: "Furiosa: A Mad Max Saga (4K Ultra HD + Digital)",
    product_price: 29.96,
    product_original_price: "$49.98",
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 130,
    product_url: "https://www.amazon.com/dp/B0D3VHPLW1",
    product_photo:
      "https://m.media-amazon.com/images/I/81cqVE2vwvL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$29.96",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery:
      "FREE delivery Mon, Aug 19 on $35 of items shipped by AmazonOr fastest delivery Tue, Aug 13 This title will be released on August 13, 2024.",
    has_variations: false,
  },
  {
    id: "0140280197",
    product_title: "The 48 Laws of Power",
    product_price: 14.55,
    product_original_price: "$26.00",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 77785,
    product_url: "https://www.amazon.com/dp/0140280197",
    product_photo:
      "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 170,
    product_minimum_offer_price: "$7.91",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "B0CQCDMY2V",
    product_title: "The Beekeeper",
    product_price: 3.99,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 24293,
    product_url: "https://www.amazon.com/dp/B0CQCDMY2V",
    product_photo:
      "https://m.media-amazon.com/images/I/91yFa4jlW0L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$3.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2024",
    delivery: null,
    has_variations: false,
  },
  {
    id: "B0CX379HYG",
    product_title:
      "Dickies Men&#x27;s Dri-tech Moisture Control No Show Socks (6/12 Pairs) (M-XXL)",
    product_price: 15.99,
    unit_price: "$2.67",
    unit_count: 6,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 17423,
    product_url: "https://www.amazon.com/dp/B0CX379HYG",
    product_photo:
      "https://m.media-amazon.com/images/I/91VLjxlAbtL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$15.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "600+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    id: "B0CW188Z2N",
    product_title: "Football League 2024",
    product_price: 7.0,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 47,
    product_url: "https://www.amazon.com/dp/B0CW188Z2N",
    product_photo:
      "https://m.media-amazon.com/images/I/81qVL2BFWhL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Feb 26, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    id: "0349132615",
    product_title: "The Housemaid&#x27;s Secret",
    product_price: 7.68,
    product_original_price: "$12.99",
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 168531,
    product_url: "https://www.amazon.com/dp/0349132615",
    product_photo:
      "https://m.media-amazon.com/images/I/81LZXcfKqJL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 58,
    product_minimum_offer_price: "$5.67",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
];
